We-Sell-Things/GraceShopper

server/db/models/index.js
server/db/models/product.js

All products tables

---

server/api/index.js
server/api/products.js

created express route to get all the producs

---

server/api/products.js

fixed products route

---

client/components/index.js
client/components/navbar.js
client/components/products.js
client/routes.js
client/store/index.js
client/store/products.js

All products front end

---

client/components/index.js
client/components/navbar.js
client/components/products.js
client/routes.js
client/store/index.js
client/store/products.js
script/seed.js
server/db/models/product.js

hi have a good day

---

client/components/products.js
client/routes.js
client/store/products.js
server/api/products.js

edited thunk to make products show

---

client/components/products.js

product components are now NavLinks

---

client/components/products.js
client/routes.js
client/store/index.js
client/store/products.js
client/store/singleProduct.js
script/seed.js
server/api/products.js

Updated Store for Single Product

---

public/index.html

title now has project name

---

client/components/SingleProduct.js
client/routes.js
client/store/singleProduct.js

added SingleProduct component

---

client/components/navbar.js
package-lock.json
package.json
public/index.html

header styling

---

server/db/models/cart.js
server/db/models/index.js

added cart model and associations

---

client/components/products.js
server/index.js

added middleware creating cart on session/ a little styling

---

client/components/SingleProduct.js
server/db/models/product.js

- Updated Product model
- Updated SingleProduct component

Updated code according code review

---

client/components/products.js
client/store/cart.js
server/api/cart.js

button runs addToCart thunk, route works

---

server/index.js

session cart persists between browser closings

---

client/components/products.js

styling on products page

---

client/components/filterSearchBar.js
client/components/products.js

productcomp

---

client/components/cart.js
client/store/cart.js
server/api/cart.js

fixed render delete

---

client/components/cart.js
client/store/cart.js

add button from cart works now

---

client/components/cart.js
server/api/cart.js

Cart eliminates products if quantity=0 in the backend.

Edit cart background route

---

server/auth/github.js

can now log in with google account

---

client/components/cart.js

Reverted some changes

---

tests/frontend/frontend-tests.js

initial test for fetching products

---

server/db/models/index.js
server/db/models/review.js
tests/backend/backend-tests.js

Review model#109

---

server/api/products.js
tests/backend/backend-tests.js

fetching a product by id now eagerly loads reviews for the product + single product route test

---

script/seed.js

added seeds for 2 reviews

---

server/api/cart.js
server/db/models/cart.js

when logged in, the cart is saved in db.

adds cart to db when logged in

---

client/components/Reviews.js
client/components/SingleProduct.js
tests/backend/backend-tests.js

groundwork for reviews component and fix to getter method test

---

server/db/models/order.js

- renamed price su subtotal
- merged productId and quantity to be an object

updated orders model

---

client/components/Reviews.js
client/components/SingleProduct.js

Review component#119

---

client/store/cart.js
client/store/categories.js
client/store/products.js
client/store/user.js
package.json
tests/frontend/frontend-tests.js

react/redux tests for User, Product, Category, Cart

wrote some frontend tests

---

server/api/orders.js
server/api/users.js

Updated security
